### PR TITLE
Week four

### PR DESCRIPTION
**Pull request by MattLuceen**
Adds week four to UCS:JS, all about data types (string, number), math (using `Number()`), and code comments.

| Activity | Time |
|-|-|
| Review: Blooket | 10m |
| Lecture: Data Types | 15m |
| Activity: Cups and Scraps | 10m |
| Code-Along: Math! | 15m |
| Survey | 5m |

### CODE REVIEW

**Review by josephmaxwellhyland — COMMENTED** [review]
Everything looks good to me! My one concern is that we might not get through all of this though... what do you think about splitting this lesson up into two weeks? That way, we could also add some review from the previous weeks (I imagine it's going to be tough to get them back in gear after spring break). Overall, I'm good with this and I know we're going to have to adjust either way. Up to you - what you have is great, and I just want to make sure we have time for it all!

**Comment by MattLuceen** [comment]
Thanks! I think if we can keep Cups 'n' Scraps timeboxed appropriately we'll be okay. We could also skip the review PPT at the end if the kids are struggling with the code along.

I looked briefly for a review blooket to stick at the beginning but didn't see any that I loved... might be good to have a refresher of some kind before diving into powerpoints. 🤔

**Comment by MattLuceen** [comment]
I am creating a review blooket for the icebreaker and will bump the review ppt to next week (unless there is time for it).

**Comment by hylandtechoutreach** [comment]
Merging, but still open to feedback!

**Pull request merged**
